### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by aledj2**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_lofreq/1)

### CODE REVIEW

**Review by andyb3 — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_lofreq/1)* status: all files reviewed, 4 unresolved discussions (waiting on @aledj2)

___
*[dxapp.json, line 39 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_lofreq/1#-LS0GaNS5812dRPgTOCh:-LS0GaNTE9VUvtO-gQ0u:b-nqoid9) ([raw file](https://github.com/moka-guys/dnanexus_lofreq/blob/457e30c11e77e6cbd3af777c92c3dd41f9ece64a/dxapp.json#L39)):*
> ```JSON
>       "class": "file",
>       "patterns": ["*.fa.gz", "*.fasta.gz","*fasta-index.tar.gz"],
>       "suggestions": [
> ```

How do suggestions work? Don't think I've used them before

Also why all the different regions below?
___
*[dxapp.json, line 96 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_lofreq/1#-LS0H8ZBAzFut6e3x3ym:-LS0H8ZBAzFut6e3x3yn:bet2dcz) ([raw file](https://github.com/moka-guys/dnanexus_lofreq/blob/457e30c11e77e6cbd3af777c92c3dd41f9ece64a/dxapp.json#L96)):*
> ```JSON
>     "interpreter": "bash"
>   },
>   "regionalOptions": {
> ```

How does it decide which of the below regions to use? I think we meant to always use aws:us-east-1
___
*[src/code.sh, line 18 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_lofreq/1#-LS0Kf0i2fHPzF58p3PP:-LS0Kf0i2fHPzF58p3PQ:b4tbind) ([raw file](https://github.com/moka-guys/dnanexus_lofreq/blob/457e30c11e77e6cbd3af777c92c3dd41f9ece64a/src/code.sh#L18)):*
> ```Shell
> # rename genome files to grch37 so that the VCF header states the reference to be grch37.fa, which then allows Ingenuity to accept the VCFs (otherwise VCF header would have reference as genome.fa which Ingenuity won't accept)
> mv genome/*.fa genome/grch37.fa
> mv genome/*.fa.fai genome/grch37.fa.fai
> ```

If this is hardcoded to use build 37, could you add something to the README and the input spec in the JSON to make it clear that ref genome has to be build 37? Or maybe it would be better t change it so that reference genome isn't an input at all, the app just downloads the build 37 reference automatically
___
*[src/code.sh, line 48 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_lofreq/1#-LS0LbYBEPK5G29pgEcd:-LS0LbYBEPK5G29pgEce:b9wawju) ([raw file](https://github.com/moka-guys/dnanexus_lofreq/blob/457e30c11e77e6cbd3af777c92c3dd41f9ece64a/src/code.sh#L48)):*
> ```Shell
> 
> # check if bedfile is provided and add to command
> if [ "$bedfile" != "" ]; then
> ```

Why does this if use single square brackets whereas above uses double?

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_lofreq/1)* status: all files reviewed, 4 unresolved discussions (waiting on @andyb3)

___
*[dxapp.json, line 39 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_lofreq/1#-LS0GaNS5812dRPgTOCh:-LS0NArI9SXkVgi5_FUN:b-1ofayo) ([raw file](https://github.com/moka-guys/dnanexus_lofreq/blob/457e30c11e77e6cbd3af777c92c3dd41f9ece64a/dxapp.json#L39)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

How do suggestions work? Don't think I've used them before

Also why all the different regions below?
</blockquote></details>

the suggestions are a list of projects that appear in green at the bottom of the page where you select the input file. I didn't spot that but if this was something we were running often manually could add in 001_here - as this will be set in the upload agent file these aren't useful and will be deleted.
___
*[dxapp.json, line 96 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_lofreq/1#-LS0H8ZBAzFut6e3x3ym:-LS0OH4c4cwfdA8KmOQA:b-lhzosv) ([raw file](https://github.com/moka-guys/dnanexus_lofreq/blob/457e30c11e77e6cbd3af777c92c3dd41f9ece64a/dxapp.json#L96)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

How does it decide which of the below regions to use? I think we meant to always use aws:us-east-1
</blockquote></details>

I think the regions are set at a project level  and at a user level. I only have access to the us-east1 region. This app is based on one made by Nexus so I guess this is needed to be used by all users. 
___
*[src/code.sh, line 18 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_lofreq/1#-LS0Kf0i2fHPzF58p3PP:-LS0PCGg2PBj06ChJufq:bes1gmt) ([raw file](https://github.com/moka-guys/dnanexus_lofreq/blob/457e30c11e77e6cbd3af777c92c3dd41f9ece64a/src/code.sh#L18)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

If this is hardcoded to use build 37, could you add something to the README and the input spec in the JSON to make it clear that ref genome has to be build 37? Or maybe it would be better t change it so that reference genome isn't an input at all, the app just downloads the build 37 reference automatically
</blockquote></details>

have stated in bed file and json
___
*[src/code.sh, line 48 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_lofreq/1#-LS0LbYBEPK5G29pgEcd:-LS0Pfq87EaNSbLuzeEB:b-w3h1kk) ([raw file](https://github.com/moka-guys/dnanexus_lofreq/blob/457e30c11e77e6cbd3af777c92c3dd41f9ece64a/src/code.sh#L48)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Why does this if use single square brackets whereas above uses double?
</blockquote></details>

good spot, fixed. (single and double brackets are nearly the same - double brackets has more functionality, including setting an exit status) - https://unix.stackexchange.com/questions/306111/what-is-the-difference-between-the-bash-operators-vs-vs-vs

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_lofreq/1)* status: 9 of 12 files reviewed, 4 unresolved discussions (waiting on @andyb3)

___
*[src/code.sh, line 18 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_lofreq/1#-LS0Kf0i2fHPzF58p3PP:-LS0SsWF9s5pefFsC5ed:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_lofreq/blob/457e30c11e77e6cbd3af777c92c3dd41f9ece64a/src/code.sh#L18)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

have stated in bed file and json
</blockquote></details>

Done.

**Review by andyb3 — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_lofreq/1)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
